services:
  - type: web
    name: autoboy-backend
    env: go
    rootDir: autoboy-backend
    buildCommand: go build -o main .
    startCommand: ./main
    plan: free
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: # Set in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://autoboy-frontend.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: # Set in Render dashboard
      - key: SMTP_PASSWORD
        value: # Set in Render dashboard
      - key: EMAIL_FROM
        value: # Set in Render dashboard
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW_MINUTES
        value: 15
      - key: AUTH_RATE_LIMIT_REQUESTS
        value: 5
      - key: AUTH_RATE_LIMIT_WINDOW_MINUTES
        value: 1
      - key: API_RATE_LIMIT_REQUESTS
        value: 1000
      - key: API_RATE_LIMIT_WINDOW_HOURS
        value: 1